
auth.token=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

defaults.org=pesa-list
defaults.project=react-native

defaults.url=https://sentry.io/
